spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@cluster0.io3s2ai.mongodb.net/
      database: ApiDatabase

server:
  port: 8080

resilience4j.retry:
  instances:
    clientRetry:
      maxAttempts: 3
      waitDuration: 2s

rest:
  cadastro: http://localhost:8082/cadastro/consult/
  bacen: http://localhost:8081/transaction/informed